### ISSUE TITLE
let expoered json schema support unhandled meta info

### ISSUE THREAD

**Issue by bluelovers** [sodaru/yup-to-json-schema#10] opened 2023-01-05 06:31 UTC
expected

```js
jsonSchema.meta = shape.spec.meta
```

**Comment by Raaghu** [comment] 2023-01-11 05:38
@bluelovers is the keyword `meta` is supported by JSON Schema. Point to specifications/documentation/reference about `meta` in JSON Schema or any JSON Schema Libraries.

**Comment by bluelovers** [comment] 2023-01-11 13:50
i don't know, but `ajv` is allow add it

**Comment by Raaghu** [comment] 2023-01-19 14:49
I need some time implement this

**Comment by Raaghu** [comment] 2023-01-20 13:58
Duplicate of #11

**Closed as completed by Raaghu** 2023-01-20 13:58 UTC
Labels: duplicate
